library("jsonlite")
library("curl")
library("tm")
library("SnowballC")
library("wordcloud")
json_data <- fromJSON("https://api.mlab.com/api/1/databases/heroku_7h57wcf3/collections/wordCloud?apiKey=N4A8HYsNTSKcAVlh-orOo01hTK9kZZwT")
jsonCorpus <- Corpus(VectorSource(json_data$last_name))
jsonCorpus <- tm_map(jsonCorpus, PlainTextDocument)
jsonCorpus <- tm_map(jsonCorpus, removePunctuation)
jsonCorpus <- tm_map(jsonCorpus, removeWords, stopwords('english'))
jsonCorpus <- tm_map(jsonCorpus, stemDocument)
png(filename = 'wordcloud.png')
wordcloud(jsonCorpus, max.words = 100, random.order = FALSE)
dev.off()
